config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users do
    resources :addresses
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :user
	REGEX_ZIPCODE_VALIDATOR = /\d{5}(?:[-\s]\d{4})?/
	validates :street_1, presence: true,
			  length: { in: 2..100 }
	validates :city, presence: true,
			  length: { in: 2..25 }
	validates :state, presence: true,
			  length: { in: 2..20}
	validates :zip_code, presence: true,
			  format: { with: REGEX_ZIPCODE_VALIDATOR }
	validates :current, inclusion: { in: [0, 1]}
	enum type_address: [:home, :work]
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :addresses
	REGEX_SSI_VALIDATOR = /\d{3}-\d{2}-\d{4}/
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	validates :ssi, presence: true, uniqueness: true, 
	format: { with: REGEX_SSI_VALIDATOR }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  helper AddressesHelper
  before_action :set_user, only:[:index, :new, :edit, :create, :update]
  before_action :set_address, only:[:edit, :update]

  def index
    @addresses = @user.addresses.all
  end

  def create 
    address = Address.new(address_params)
    if address.current == 1
      intTypeAddress = address.type_address == 'work' ? 1 : 0
      Address.where('type_address = ? AND id <> ?', intTypeAddress, params[:id]).update_all( current: 0)
    end
    @address = @user.addresses.new(address_params)
    if @address.save!
      flash[:success] = "Address saved successfully!"
      redirect_to user_addresses_path(@user)
    else
      flash[:danger] = "Unable to saved address!"
      redirect_to @address
    end
  end

  def new
    @address = Address.new
  end

  def edit 
  end

  def destroy
  end

  def update
    address = Address.new(address_params)
    if address.current == 1
      intTypeAddress = address.type_address == 'work' ? 1 : 0
      Address.where('type_address = ? AND id <> ?', intTypeAddress, params[:id]).update_all(current: 0)
    end
    @address.update_attributes(address_params)
    if @address.save
      flash[:success] = "Address updated successfully!"
      redirect_to user_addresses_path(@user)
    else
      flash[:danger] = "Unable to update address!"
      redirect_to @address
    end
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_address
      @address = @user.addresses.find(params[:id])
    end

    def address_params
      params.require(:address).permit(:street_1, :street_2, :city, :state, :zip_code, :current, :type_address)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper UsersHelper
  before_action :set_user, only:[:edit, :destroy, :update]
  def new
    @user = User.new
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to root_url
  end


  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User saved successfully!"
      redirect_to root_url
    else
      flash[:danger] = "Unable to saved user!"
      redirect_to @user
    end
  end

  def destroy
    @user.destroy
    redirect_to @users
  end

  def index
    @users = User.all
  end

 

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :ssi)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
	def user_address_title(user)
		"#{user.first_name} #{user.last_name} Addresses"
	end

	def add_address_title
		"Add An Address"
	end

	def edit_address_title
		"Edit Address"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
	def edit_user_title
		"Edit User"
	end

	def home_page_title
		"Home Page Directory"
	end

	def new_user_title
		"Add New User"
	end
end

app/helpers/users_helper.rb
module UsersHelper
	def edit_user_title
		"Edit User"
	end

	def home_page_title
		"Home Page Directory"
	end

	def new_user_title
		"Add New User"
	end
end

app/views/addresses/edit.html.erb
<% provide(:title, edit_address_title)%>

<%= render "shared/add_address_form"%>
<br>
<% link_to 'All Addresses', user_addresses_path(@user) , method: :get, class: "btn btn-primary" %>

app/views/addresses/index.html.erb
<% provide(:title, user_address_title(@user)) %>

<%= render 'shared/user_addresses' %>

<%= link_to 'Add Address',  new_user_address_path(@user), method: :get, class: "btn btn-primary" %>
<br><br>
<%= link_to 'All Users', root_url, method: :get, class: "btn btn-primary" %>

app/views/addresses/new.html.erb
<% provide(:title, add_address_title)%>

<%= render 'shared/add_address_form' %>
<br>
<% link_to 'All Addresses', user_addresses_path(@user) , method: :get, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsersAddress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<h1 class="container"><%= yield(:title) %></h1>
	<header class="container">
		<% flash.each do |message_type, message |%>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
	</header>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/shared/_add_address_form.html.erb
<%= form_for([@user , @address])  do |f_address| %>
	<% if @address.errors.any? %>
		<div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  	<% end %>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<td><%= f_address.label :street_1 %>:</td>
			<td><%= f_address.text_field :street_1 %></td>
		<tr>
		<tr>
			<td><%= f_address.label :street_2 %>:</td>
			<td><%= f_address.text_field :street_2 %></td>
		<tr>
		<tr>
			<td><%= f_address.label :city %>:</td>
			<td><%= f_address.text_field :city %></td>
		<tr>
		<tr>
			<td><%= f_address.label :state %>:</td>
			<td><%= f_address.text_field :state %></td>
		<tr>
		<tr>
			<td><%= f_address.label :zip_code %>:</td>
			<td><%= f_address.text_field :zip_code %></td>
		<tr>
		<tr>
			<td><%= f_address.label :address_type %></td>
			<td><%= f_address.select(:type_address, options_for_select([['home','home'],['work','work']])) %></td>
		</tr>
		<tr>
			<td><%= f_address.label :current %></td>
			<td><%= f_address.check_box :current, :checked_value => 1, :unchecked_value => 0 %></td>
		</tr>
	</table>
	<br>
	<%= f_address.submit class: "btn btn-primary" %>
<% end %>
<br>

app/views/shared/_form_for_user.html.erb
<% if @users.empty? %>
	<h1>No records </h1>
<% else %>
<table class="table table-condensed table-striped">
	<tr>
		<th colspan="1">User</th>
		<th colspan="1">Edit User</th>
		<th colspan="1">Delete User</th>
		<th colspan="1">User Addresses</th>
	</tr>
	<% @users.each do |user| %>
		<tr>
			<td><%=user.first_name%> <%=user.last_name%></td>
			<td><%=link_to 'Edit', edit_user_path(user) %></td>
			<td><%=link_to 'Delete', user_path(user), method: :delete %></td>
			<td><%=link_to 'Addresses', user_addresses_path(user) %></td>
		</tr>
	<% end %>
</table>
<% end %>


app/views/shared/_new_user_form.html.erb
<%= form_for(@user)  do |f_user| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  	<% end %>
	<table class="table table-striped">
		<tr>
			<td><%= f_user.label :first_name %>:</td>
			<td><%= f_user.text_field :first_name %></td>
		<tr>
		<tr>
			<td><%= f_user.label :last_name %>:</td>
			<td><%= f_user.text_field :last_name %></td>
		<tr>
		<tr>
			<td><%= f_user.label :social_security_number %>:</td>
			<td><%= f_user.text_field :ssi %></td>
		<tr>
	</table>
	<br>
	<%= f_user.submit class: "btn btn-primary" %>
<% end %>
<br>

app/views/shared/_user_addresses.html.erb
<% if @addresses.empty? %>
	<h2>User has no addresses</h2>
<% else %>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th colspan="1u">Street 1</th>
			<th colspan="1">Street 2</th>
			<th colspan="1">City</th>
			<th colspan="1">State</th>
			<th colspan="1">Zip Code</th>
			<th colspan="1">Address Type</th>
			<th colspan="1">Current</th>
			<th colspan="1">Edit User</th>
		</tr>
		<% @addresses.each do |address| %>
			<tr>
				<td><%= address.street_1 %></td>
				<td><%= address.street_2 %></td>
				<td><%= address.city %></td>
				<td><%= address.state %></td>
				<td><%= address.zip_code %></td>
				<td><%= address.type_address %></td>
				<% if address.current == 1 %>
					<td>Current Address</td>
				<% else %>
					<td>Not Current</td>
				<% end %>
				<td><%= link_to "Edit", edit_user_address_path(@user, address) %></td>

			</tr>
		<% end %>
	</table>
<% end %>

app/views/users/edit.html.erb
<%= provide(:title, edit_user_title) %>

<%= render 'shared/new_user_form' %>

app/views/users/index.html.erb
<% provide(:title, home_page_title) %>

<%= render 'shared/form_for_user' %>

<%= link_to "Add User", new_user_path, :method => :get, class: "btn btn-primary" %>

app/views/users/new.html.erb
<% provide(:title, new_user_title) %>

<%= render 'shared/new_user_form' %>

<%= link_to 'All Users', root_url, class: "btn btn-primary" %>